services:
  caddy:
    image: caddy
    container_name: "caddy"
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "caddy_data:/data"
      - "caddy_config:/config"
      - "./Caddyfile:/etc/caddy/Caddyfile"
    networks:
      - "shop_nt"
  db:
    image: postgres
    container_name: "db"
    environment:
      - "POSTGRES_PASSWORD=qwerty"
      - "POSTGRES_DB=pd411_shop"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - "shop_db:/var/lib/postgresql"
    networks:
      - "shop_nt"

  api:
    build: "back/"
    image: potapchuk22/pd411_shop_api
    container_name: "shop_api"
    environment:
      - "ConnectionStrings__LocalDb=User ID=postgres;Password=qwerty;Host=db;Port=5432;Database=pd411_shop;"
      - "EnableSwagger=true"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - "shop_api:/app/Storage"
    networks:
      - "shop_nt"
  web:
    build:
      context: "front/"
      args:
        API_URL: "https//api.pd411.pp.ua/api/"
        IMAGE_URL: "https://api.pd411.pp.ua/image/"
    image: potapchuk22/pd411_shop_web
    container_name: "shop_web"
    networks:
      - "shop_nt"

networks:
  shop_nt:
    name: "shop_nt"

volumes:
  shop_db:
    name: "shop_db"
  shop_api:
    name: "shop_api"
  caddy_data:
    name: "caddy_data"
  caddy_config:
    name: "caddy_config"
